# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
estep_lmm_cpp <- function(res_fixed, Z, group_indicator, inv_Omega, sigma2, J) {
    .Call(`_emlmm_estep_lmm_cpp`, res_fixed, Z, group_indicator, inv_Omega, sigma2, J)
}

#' @export
log_lik_lmm_cpp <- function(y, Z, X, group_indicator, beta, Omega, sigma2, J) {
    .Call(`_emlmm_log_lik_lmm_cpp`, y, Z, X, group_indicator, beta, Omega, sigma2, J)
}

#' @export
estep_mlmm_cpp <- function(vec_res_fixed, Z, group_indicator, vec_group_indicator, inv_Psi, I_r, inv_Sigma, r, J) {
    .Call(`_emlmm_estep_mlmm_cpp`, vec_res_fixed, Z, group_indicator, vec_group_indicator, inv_Psi, I_r, inv_Sigma, r, J)
}

#' @export
log_lik_mlmm_cpp <- function(vec_Y, Z, vec_XB, group_indicator, vec_group_indicator, PSI, SIGMA, I_r, J) {
    .Call(`_emlmm_log_lik_mlmm_cpp`, vec_Y, Z, vec_XB, group_indicator, vec_group_indicator, PSI, SIGMA, I_r, J)
}

